@startuml
object View

View <|-- ViewGroup

ViewGroup <|-- GirdView
ViewGroup <|-- AbsoluteLayout
ViewGroup <|-- LinearLayout
ViewGroup <|-- FrameLayout
ViewGroup <|-- RelativeLayout

LinearLayout <|-- TableLayout
@enduml